Mobile and desktop capstone
NeckerFree/Capstone-Module-1 pull request #1
Opened 2022-03-18 00:32 UTC by NeckerFree

**Capstone Module 1 Project**

_Objectives:_
- Use HTML tags and apply best practices.
- Use CSS selectors and box model.
- Use Flexbox to place elements on the page.
- Create UIs adaptable to different screen sizes using media queries.
- Use GitHub Pages to deploy web pages.
- Use JavaScript to manipulate DOM, create events, use objects to store data,  and apply best practices.
- Communicate technical concepts to other technical people.

2022-03-18 14:37 UTC, mateo951 requested changes
### Hi @NeckerFree, 

📝👌 **Your project highlights** 🔥😎 
- General Requirements ✔
- JS implementation for dynamic object creation ✔

You have done a very good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-18 14:37 UTC, mateo951 commented on README.md
> + [Description Video](https://www.loom.com/share/614b1a95b24c415d912f3d65e43da00f)
Please add your description video into your PR's description 📝

![image](https://user-images.githubusercontent.com/15807343/159016305-26345611-1e2a-44df-8240-a294beae100b.png)

2022-03-18 14:37 UTC, mateo951 commented on README.md
Kindly add an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-03-18 14:37 UTC, mateo951 commented on about.html
> +            <div class="animated-icon1"><span></span><span></span><span></span></div>
Kindly remove the border of your hamburger button to improve the resemblance of your design with the given design 

### Yours
![image](https://user-images.githubusercontent.com/15807343/159018200-9a383dba-e102-45b7-8124-161b1ddf9626.png)

### Cindy's Design
![image](https://user-images.githubusercontent.com/15807343/159018244-44eac39b-343d-4820-b17c-1ff414552db3.png)

2022-03-18 14:37 UTC, mateo951 commented on about.html
> +        </div>
Ideally, we should aim for almost identical designs as much as possible to meet the project requirements 🧐 Please make the necessary changes so that your desktop-navbar follows Cyndy's design. You could change your CSS so that the navbar occupies the whole width and also give it a little bit more padding so that your elements have more space 🔥

### Yours
![image](https://user-images.githubusercontent.com/15807343/159018941-6c1b6fc8-b3ba-4a87-b57f-c42a0a561623.png)
Cindy's Design
![image](https://user-images.githubusercontent.com/15807343/159018767-40aafc39-15ad-40a3-a5c4-d07120c2ffc6.png)

2022-03-18 14:37 UTC, mateo951 commented on index.html
> +
Kindly make sure that your home page has a partner section and a footer 😉

2022-03-18 14:37 UTC, mateo951 commented on index.html
> +  </article>
It's important that your design gets as close as possible to Cindy's so that you can sharpen your HTML/CSS skills as much as possible. Try giving the main title a bit of margin so it separates from the navbar. Also, add some bottom margin to your `lowSection` so that everything has a bit more air before the next section 🚀 Please make the mentioned changes so that your project meet the requirements 🙌

### Yours 
![Captura1](https://user-images.githubusercontent.com/15807343/159019942-3ee791b6-8e25-4b98-af9e-2045b9a5681f.PNG)


### Cindy's Design 
![image](https://user-images.githubusercontent.com/15807343/159019889-b14f302e-a323-4423-9bd0-3f838476ed20.png)

2022-03-18 14:37 UTC, mateo951 commented on index.html
> +    </section>
Due to semantics reasons, each class card should be wrapped in an article tag 🧐 Kindly change your sections into articles 😁

2022-03-18 14:37 UTC, mateo951 commented on css/styles.css
> +  --cap-gray-color: #d3d3d3;
The pages use the exact same colors, for text, backgrounds, borders, etc, from the original design 👍

2022-03-18 14:37 UTC, mateo951 commented on css/styles.css
> +@import url('https://fonts.googleapis.com/css2?family=Lato');
Proper fonts where used 💪😎 Well done 🔥

2022-03-18 14:37 UTC, mateo951 commented on js/scriptCode.js
> +  }
Iterates through the speakers list and creates HTML elements with the data from each object 💣✔

2022-03-19 14:39 UTC, NeckerFree commented on css/styles.css
> +  --cap-gray-color: #d3d3d3;
@mateo951 : Yes, you can get the exact color using the Chrome Eye Dropper extension.

2022-03-19 16:34 UTC, elmar8287 approved these changes
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 16:41 UTC, merged